name: CI - Build, Test (Docker & Pytest)

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies (for quick fail-fast local test)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest -q

      - name: Build Docker images (runtime & test)
        run: |
          docker build --target runtime -t aceest/fitness-api:runtime .
          docker build --target test -t aceest/fitness-api:test .

      - name: Run tests inside Docker image
        run: |
          docker run --rm aceest/fitness-api:test
